#!/bin/bash
set -e

case "$1" in
  install)
    # 0. docker run --rm -v /usr/local/bin:/target/bin -v /usr/share:/target/share pkinsky/boot install
    echo "1. backup xmonad.desktop if it exists"
    mv /target/share/xsessions/xmonad.desktop /target/share/xsessions/xmonad.desktop.old || true
    echo "2. copy in new xmonad.desktop to /usr/share/xsessions/"
    cp /resources/xmonad.desktop /target/share/xsessions/
    echo "3. copy cool png badge to /usr/share/unity-greeter/"
    cp ~/resources/custom_xmonad_badge.png /target/share/unity-greeter/
    echo "4. copy dxmonad to /usr/local/bin/"
    install -m 0755 /resources/bin/dxmonad /target/bin/
    echo "5. copy dockerui to /usr/local/bin/"
    install -m 0755 /resources/bin/dockerui /target/bin/
    echo "6. copy maersk to /usr/local/bin/"
    install -m 0755 /resources/bin/maersk /target/bin/
    echo "7. copy dx-mysql to /usr/local/bin/"
    install -m 0755 /resources/bin/dx-mysql /target/bin/
    ;;
  uninstall)
    # todo
    ;;
  bash)
    # useful fallback for container diagnostics
    exec $@
    ;;
esac
