#!/bin/bash

PATH=/usr/sbin:/usr/bin:/sbin:/bin

if [ "$1" == "r" ]; then
  docker stop dockerui || true
  docker kill dockerui || true
  docker rm   dockerui || true
fi
docker run -d \
  --name dockerui \
  --volume=/var/run/docker.sock:/var/run/docker.sock \
  dockerui/dockerui || docker start dockerui
