#!/bin/bash

PATH=/usr/sbin:/usr/bin:/sbin:/bin

prog=$(basename $0)
exec=$(which $prog)

if [ -n "${exec}" ]; then
  exec ${exec} $@
else
  USER_UID=$(id -u)
  USER_GID=$(id -g)

  docker stop dockerui || true
  docker kill dockerui || true
  docker run -d \
    --name dockerui \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    dockerui/dockerui

  echo "Starting ${prog}..."
  docker run \
    --link dockerui:dockerui \
    --link anchor:anchor\
    --env USER_UID=${USER_UID} \
    --env USER_GID=${USER_GID} \
    --env DISPLAY=${DISPLAY} \
    --volume=/home/pkinsky/.mozilla:/home/dev/.mozilla \
    --volume=/home/pkinsky/.ssh:/home/dev/.ssh \
    --volume=/home/pkinsky/dxmonad:/home/dev/dxmonad \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    --volume=/tmp/.X11-unix:/tmp/.X11-unix \
    --volume=/run/user/${USER_UID}/pulse:/run/pulse \
    pkinsky/dxmonad:latest
fi
