#!/bin/bash

PATH=/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin

USER_UID=$(id -u)
USER_GID=$(id -g)

echo "starting dockerui"
dockerui

echo "starting maersk"
maersk


docker kill dxmonad
docker rm   dxmonad
echo "Starting dxmonad..."
docker run \
    --name dxmonad \
    --volumes-from maersk \
    --link dockerui:dockerui \
    --env USER_UID=${USER_UID} \
    --env USER_GID=${USER_GID} \
    --env DISPLAY=${DISPLAY} \
    --volume=/home/pkinsky/.mozilla:/home/dev/.mozilla \
    --volume=/home/pkinsky/.ssh:/home/dev/.ssh \
    --volume=/home/pkinsky/dxmonad:/home/dev/dxmonad \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    --volume=/tmp/.X11-unix:/tmp/.X11-unix \
    --volume=/run/user/${USER_UID}/pulse:/run/pulse \
    pkinsky/dxmonad:latest
