#!/bin/bash
# xmonad "startup hook" script. This gets run after xmonad is initialized,

# Empathy chat client (-h: start hidden, -n: don't connect on launch)
#if [ -z "$(pgrep empathy)" ] ; then
#    empathy -h -n &
#fi

# currently broken
# Network manager, so we don't have to configure wifi at the command line.
# if [ -z "$(pgrep nm-applet)" ] ; then
#    nm-applet --sm-disable &
# fi

# Applet for managing print jobs from the tray.
#if [ -z "$(pgrep system-config-printer-applet)" ] ; then
#    system-config-printer-applet &
#fi

# On login, we unlock the ssh keychain so we're not prompted for 
# passphrases later. We pipe /dev/null to ssh-add to make it realize 
# it's not running in a terminal. Otherwise, it won't launch the prompt.
#
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.

# export SSH_ASKPASS="/usr/bin/ssh-askpass"
# cat /dev/null | ssh-add &
